### PR TITLE
Move to GitHub actions

### PR DESCRIPTION
**Pull request by mstimberg**
This replaces travis and appveyor by [GitHub Actions](https://github.com/spyking-circus/spyking-circus/actions) and simplifies the whole testing/deployment setup along the way.

There are four "workflow" files (in principle it could be a single one, but you can only restart complete workflows, so it can be useful to have them split up):
<dl>
<dt>Build and publish PyPI packages</dt>
<dd>Builds the source package and the wheel, and tries to install from these packages via pip</dd>
<dt>Tests on Linux/Windows/OS X</dt>
<dd>Builds the conda package on the respective OS for Python 3.6, 3.7, 3.8. The only test at the moment is trying to import the package and running `spyking-circus -h`.</dd>
</dl>

I did not bother with Python 2 support for now, do you still want to keep it? If not, it might be worth getting rid of the `2to3.py` clutch as well... Oh, and on Windows we cannot build a conda package for Python 3.8 due to dependency issues, but it might just be because there is no `mpi4py` package for Python 3.8 in the `intel` channel?

All of these workflows should upload the respective PyPI/conda packages if you tag a new release, but obviously I did not test this yet :) It also still needs a bit additional configuration for the tokens:
* Create an API token on PyPI: https://pypi.org/help/#apitoken
* Add it as a "secret" named `pypi-password` to the repository: https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository
* Create a token for Anaconda with "scope" for read and write access to the API: https://anaconda.org/spyking-circus/setting/access
* Add this token as another secret, called `ANACONDA_TOKEN`

I also wonder (but this would be a separate PR once the general setup is working) whether it would make sense to switch to [`versioneer`](https://github.com/python-versioneer/python-versioneer). If this works, it would mean that you'd never have to update the version number manually, just tagging the release would be enough (and even users that use `spyking-circus` directly from github would have a meaningful version number).

### CODE REVIEW

**Comment by yger** [comment]
Thanks so much ! Open to any suggestion for versioneer. I'll try to follow your steps next Monday, asap, and let you know how it goes

**Comment by yger** [comment]
Sould I delete the .yaml for travis and appveyor? And also, the token name is PYPI_PASSWORD, since it was only capital letter and no "-" symbol. Hope this is fine

**Comment by mstimberg** [comment]
> Sould I delete the .yaml for travis and appveyor?

They are already deleted in this PR, so if you merge it they disappear :)



> And also, the token name is PYPI_PASSWORD, since it was only capital letter and no "-" symbol. Hope this is fine

It's not case sensitive actually, and the `-` was a typo `PYPI_PASSWORD` is correct!

**Comment by mstimberg** [comment]
Let's try to make a release! I'd be very surprised if it actually worked, but who knows :)

**Comment by yger** [comment]
Why not. I believe in you so much. I'll try asap. Should I also keep the conda_receipe folder then? I guess yes, since it is providing the info for conda compilation. I'll try something and we'll see

**Comment by mstimberg** [comment]
> Should I also keep the conda_receipe folder then? I guess yes, since it is providing the info for conda compilation.

Yes, `conda_recipe` is still needed.

**Comment by mstimberg** [comment]
Ok, this worked as good as I expected, i.e. it didn't :) The PyPI upload worked, but it uploaded it as 1.0.2 instead of 1.0.3 because the version in `setup.py` was not updated. The same would have been true for the conda uploads (the version in `meta.yaml` is still 1.0.2 as well), but they failed for a different reason :) I directly pushed a fix for the conda uploads to master. I'm somewhat confident that if you update the version numbers and tag a new release it might just work :smile: If all that works we can try out versioneer which would avoid "forgot to update the version number" issues in the future.

**Comment by mstimberg** [comment]
It looked like it worked :tada: I see 1.0.4 packages on PyPI and on Anaconda.org for all operating systems and Python versions (except for Windows Python 3.8 because of the dependency issue).

I'll have a look into versioneer next. If it works well I am going to use it for other packages :)

**Comment by yger** [comment]
Yes, I can see that, thanks a lot, wonderful!

**Pull request merged**
