### PR TITLE
All files reading method

### PR DESCRIPTION
**Pull request by Tom-TBT**
Hi,
the stream_mode multi-file is not what I expected. 
In the folder containing my multiple data file for 1 experiment, I would like the program to take all the files, without the need of having a code number. Also, my files have dates in the name and so there is no pattern in the name.
Please have a look to the changes I made. I don't know if it's the best way to incorporate it, do what you want with it. I just wanted to avoid to enter in conflict with your multi-file method.

Instead of looking for files that only correspond to a pattern in the folder, this all-file stream mode take all file with same extension in alphabetical order.

Cheers,
Tom Boissonnet

### CODE REVIEW

**Comment by yger** [comment]
Thanks a lot for the commit, I'll review it asap. Just to be sure, could you send me for example a list of datafiles that you have, in a given folder? I mean, at the end, I think I could make the multi-files more robust such that it reads everything in the folder with a human-like order (alphabetical by default, with/wihtout numbers at the end).

**Comment by yger** [comment]
In fact, I just created a branch robust_multi_files that should solve your problem. Could you try it and tell me if this is working for you? (assuming you know how to switch branches in git) I would rather prefer to keep a single multi-files options instead of having also all-files mode. The behavior of multi-files is therefore extended. By default, it will read all files in a given directory with the same extension, and order them alphabetically (and by final numbers at the end if any, so this should be compatible with previous mode)

**Comment by Tom-TBT** [comment]
Hi Pierre,
capture
That's the kind of files we have.
Your commit works for me. I haven't tested it until the end of the process but in the log I see that all files are here and in the right order. 
And I of course agree with this version of the multi file, instead of having two different but almost similar stream-modes ! Thanks a lot.

Cheers,
Tom

**Comment by yger** [comment]
Thanks a lot for the feedback. Then I'm merging this into master, such that
the multi-files mode is now more robust

Pierre

2018-01-18 9:45 GMT+01:00 Tom Boissonnet <notifications@github.com>:

**Pull request closed without merging**
